.TH htpasswd 1 "05 May 1998"
.SH NAME
htpasswd - manipulate HTTP-server password files
.SH SYNOPSIS
.B htpasswd
.RB [ -c ]
.I passwordfile
.I username
.SH DESCRIPTION
.PP
Sets a user's password in an httpd-style password file.
The -c flag creates a new file.
.SH AUTHOR
Rob McCool.
Modified 29aug97 by Jef Poskanzer to accept new password on stdin,
if stdin is a pipe or file.  This is necessary for use from CGI.
